import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Header1 } from "@/components/Header1";
import { Header2 } from "@/components/Header2";
import { Update } from "@/components/Update";
import { Footer } from "@/components/Footer";
import { Providers } from "./provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "e-commerce-website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Header1 />
          <Header2 />
          {children}
          <Update />
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
